# Settings for the app
app:
  # HTML Title
  title: Public Space Strategy
  # Header name
  name: Public Space Strategy
  # Meta description that will show up in Google search results
  meta_description: _(CrowdSpot creates custom maps that allow people to give input on geogrpahic locations. Use it to collect data in a social, engaging process.)

  # When the map loads, existing places will be loaded in chunks. By default,
  # the size of the chunks will be a reasonable default dictated by the API
  # server. If you would like to override the chunk size, use this setting:
  # places_page_size: 100

  # Optional. List view is supported by default. Set to false to disable.
  # list_enabled: false

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false
  options:
    center:
      lat: -37.847409 
      lng: 144.96656
    zoom: 14
    minZoom: 13
    maxZoom: 19
  layers:
    - url: http://{s}.tiles.mapbox.com/v3/aisey.jh9o1b8a/{z}/{x}/{y}.png
      attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'
    - url: /static/data/philadelphia.geojson
      type: json
      rules:
        - condition: 'true'
          style:
            color: "#042A5E"
            opacity: 0.6
            fillOpacity: 0.1
            weight: 0.5

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  happy:
    label: _(Happy Spot)
    rules:
      - condition: '"{{location_type}}" === "happy" && {{map.zoom}} < 14 && {{layer.focused}} === false'
        # Display landmarks as circles (vectors) when zoomed out

        style:
          color: '#45BA00'
          radius: 5
          weight: 1
          opacity: 0.9
          fillOpacity: 0.7

      - condition: '"{{location_type}}" === "happy" && {{map.zoom}} >= 14 && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/master-pin-happy-green1.png
          shadowUrl: /static/css/images/master-pin-shadow.png
          iconSize: [85, 41]
          iconAnchor: [42, 42]

      - condition: '"{{location_type}}" === "happy" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/marker-f95016.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]
  dislike:
    label: _(Dislike Spot)
    rules:
      - condition: '"{{location_type}}" === "dislike" && {{map.zoom}} < 14 && {{layer.focused}} === false'
        # Display landmarks as circles (vectors) when zoomed out

        style:
          color: '#FF1609'
          radius: 5
          weight: 1
          opacity: 0.9
          fillOpacity: 0.7

      - condition: '"{{location_type}}" === "dislike" && {{map.zoom}} >= 14 && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/master-pin-sad-red1.png
          shadowUrl: /static/css/images/master-pin-shadow.png
          iconSize: [85, 41]
          iconAnchor: [42, 42]

      - condition: '"{{location_type}}" === "dislike" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/marker-f95016.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]
  idea:
    label: _(Idea Spot)
    rules:
      - condition: '"{{location_type}}" === "idea" && {{map.zoom}} < 14 && {{layer.focused}} === false'
        # Display landmarks as circles (vectors) when zoomed out

        style:
          color: '#028CA7'
          radius: 5
          weight: 1
          opacity: 0.9
          fillOpacity: 0.7

      - condition: '"{{location_type}}" === "idea" && {{map.zoom}} >= 14 && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/master-pin-idea.png
          shadowUrl: /static/css/images/master-pin-shadow.png
          iconSize: [85, 41]
          iconAnchor: [42, 42]

      - condition: '"{{location_type}}" === "idea" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/marker-f95016.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]  
  activity:
    label: _(Activity Spot)
    rules:
      - condition: '"{{location_type}}" === "activity" && {{map.zoom}} < 14 && {{layer.focused}} === false'
        # Display landmarks as circles (vectors) when zoomed out

        style:
          color: '#0C4DA2'
          radius: 5
          weight: 1
          opacity: 0.9
          fillOpacity: 0.7

      - condition: '"{{location_type}}" === "activity" && {{map.zoom}} >= 14 && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/master-pin-activity.png
          shadowUrl: /static/css/images/master-pin-shadow.png
          iconSize: [85, 41]
          iconAnchor: [42, 42]

      - condition: '"{{location_type}}" === "activity" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/marker-f95016.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]     

activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: true
  add_button_label: _(Add a Spot)
  # Labels for the buttons that toggle the map and list views
  show_list_button_label: _(List All Spots)
  show_map_button_label: _(Show the Map)
  action_text: _(added)
  title: _(Please tell us about our public spaces)
  action_text: _(created)
  anonymous_name: _(Someone)
  submit_button_label: _(Submit)
  items:
    - prompt: _(Where is this public space?)
      type: text
      name: name
      attrs:
        - key: placeholder
          value: _(Park, street, etc.)
        - key: size
          value: 30
        - key: required
    - prompt: _(What type of spot are you adding at this public space?)
      type: select
      options:
        - label: _(Choose One)
          value: ''
        - label: _(Happy Spot)
          value: happy
        - label: _(Dislike Spot)
          value: dislike
        - label: _(Idea Spot)
          value: idea  
        - label: _(Activity Spot)
          value: activity   
      name: location_type
      attrs:
        - key: required   
    - prompt: _(Please tell a little more this public space)
      type: textarea
      name: description
      attrs:
        - key: placeholder
          value: _(Type here...)
        - key: required        
    - prompt: _(What is your connection to the City of Port Phillip?)
      type: select
      options:
        - label: _(Please choose)
          value: 
        - label: _(Resident)
          value: resident
        - label: _(Business Owner)
          value: business Owner
        - label: _(Rate payer)
          value: rate payer
        - label: _(Worker)
          value: worker
        - label: _(Student)
          value: student
        - label: _(Visitor)
          value: visitor
      name: connection
      attrs:
        - key: required  
          value: true       
    - prompt: _(Image)
      inputfile_label: _(Add an Image)
      type: file
      name: my_image
      optional: true
      attrs:
        - key: accept
          value: image/*           
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      optional: true
      attrs:
        - key: placeholder
          value: _(Your name will be visible)
        - key: size
          value: 30     
    - prompt: _(Your Email)
      type: text
      name: private-submitter_email
      optional: true
      attrs:
        - key: placeholder
          value: _(Used for feedback)
        - key: size
          value: 30      

survey:
  submission_type: comments

  # Response config
  show_responses: true
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
      attrs:
        - key: required
    - prompt: _(Your Name)
      type: text
      name: submitter_name

support:
  submission_type: support
  submit_btn_text: _(Support)
  response_name: _(support)
  response_plural_name: _(supports)
  action_text: supported
  anonymous_name: _(Someone)

pages:
  - title: _(Welcome)
    slug: welcome
    name: overview
    start_page: true

  - title: _(FAQs)
    slug: why
    url: /static/pages/why.html

notifications:
  on_new_place: true
  submitter_email_field: private-submitter_email