# The Shareabouts API dataset username & name used by this map.
# You MUST change this after creating a dataset.
api_root: http://localhost:8001/api/v1/
dataset: tom/bikespot

# And the associated API key.
dataset_api_key: YWY1YjMyNzU5YjRiZDljOTQwMGM0Nzhm

# Settings for the app
app:
  # HTML Title
  title: My Eco-city Map
  # Header name
  name: My Eco-city Map
  # Meta description that will show up in Google search results
  meta_description: The 'My EcoCity Map' was created for the city and its many residents and visitors to contribute and share knowledge about all the sustainable activities taking  in Central Melbourne.

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: true
  options:
    center:
      lat: -37.81361
      lng: 144.96306
    zoom: 14
    minZoom: 10
    maxZoom: 17
  base_layer:
    url: http://{s}.tiles.mapbox.com/v3/aisey.map-u8fegfjt/{z}/{x}/{y}.png
    attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'
  layers: []

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  Project Spot:
    default: orange
    focused: red
  Building Spot:
    default: green
    focused: red
  Transport Spot:
    default: blue
    focused: red
  Shopping Spot:
    default: pink
    focused: red
  Organisation Spot:
    default: aqua
    focused: red

# Defines place icons. See http://leaflet.cloudmade.com/reference.html#icon
# for documention of each property. Any omitted property will be undefined.
place_type_icons:
  blue:
    iconUrl: /static/css/images/master-pin-blue.png
    shadowUrl: /static/css/images/master-pin-shadow.png
    iconSize:
      width: 85
      height: 41
    shadowSize:
      width: 42
      height: 85
    iconAnchor:
      x: 42
      y: 42
  orange:
    iconUrl: /static/css/images/master-pin-orange.png
    shadowUrl: /static/css/images/master-pin-shadow.png
    iconSize:
      width: 85
      height: 41
    shadowSize:
      width: 42
      height: 85
    iconAnchor:
      x: 42
      y: 42
  red:
    iconUrl: /static/css/images/master-pin-red.png
    shadowUrl: /static/css/images/master-pin-shadow.png
    iconSize:
      width: 85
      height: 41
    shadowSize:
      width: 42
      height: 85
    iconAnchor:
      x: 42
      y: 42
  green:
    iconUrl: /static/css/images/master-pin-green.png
    shadowUrl: /static/css/images/master-pin-shadow.png
    iconSize:
      width: 85
      height: 41
    shadowSize:
      width: 42
      height: 85
    iconAnchor:
      x: 42
      y: 42
  pink:
    iconUrl: /static/css/images/master-pin-pink.png
    shadowUrl: /static/css/images/master-pin-shadow.png
    iconSize:
      width: 85
      height: 41
    shadowSize:
      width: 42
      height: 85
    iconAnchor:
      x: 42
      y: 42
  aqua:
    iconUrl: /static/css/images/master-pin-aqua.png
    shadowUrl: /static/css/images/master-pin-shadow.png
    iconSize:
      width: 85
      height: 41
    shadowSize:
      width: 42
      height: 85
    iconAnchor:
      x: 42
      y: 42


activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 5000

place:
  adding_supported: true
  add_button_label: Add a Spot
  action_text: added
  title: Tell us more...
  action_text: created
  anonymous_name: Someone
  submit_button_label: Submit
  items:
    - prompt: Spot Name
      type: text
      name: name
      attrs:
        - key: placeholder
          value: Spot Name
        - key: size
          value: 30
    - prompt: Spot Type
      type: select
      options:
        - Project Spot
        - Building Spot
        - Transport Spot
        - Shopping Spot
        - Organisation Spot
      name: location_type
    - prompt: Spot Address
      type: text
      name: address
      optional: false
      attrs:
        - key: placeholder
          value: Type address here
        - key: size
          value: 30
    - prompt: Your Name or Organisation Name
      type: text
      name: submitter_name
      attrs:
        - key: placeholder
          value: Type name here
        - key: size
          value: 30
    - prompt: Spot Link
      type: text
      name: link
      optional: true
      attrs:
        - key: placeholder
          value: Type web link here (include http:// for hyperlink)
        - key: size
          value: 30
    - prompt: Description
      type: textarea
      name: description
      optional: true
      attrs:
        - key: placeholder
          value: Description...

survey:
  submission_type: comments

  # Response display config
  show_responses: true
  response_name: comment
  response_plural_name: comments
  action_text: commented on
  anonymous_name: Someone

  # Survey form config
  title: Leave a Comment
  form_link_text: Leave a Comment
  submit_btn_text: Comment
  items:
    - prompt: Comment
      label: Comment
      type: textarea
      name: comment
    - prompt: Your Name
      type: text
      name: submitter_name

support:
  submission_type: support
  submit_btn_text: Support This!
  action_text: "supported"
  anonymous_name: Someone

pages:
  - title: About
    slug: about
    url: /static/pages/overview.html
    start_page: true

  - title: The Spots
    slug: spots
    url: /static/pages/why.html

  - title: Filter Spots
    pages:
      - title: All
        external: true
        url: /

      - title: Project Spots
        external: true
        url: /project spot

      - title: Building Spots
        external: true
        url: /building spot

      - title: Transport Spots
        external: true
        url: /transport spot

      - title: Shopping Spots
        external: true
        url: /shopping spot

      - title: Org Spots
        external: true
        url: /orgnisation spot

  - title: FAQs
    slug: faqs
    url: /static/pages/features.html

  - title: CrowdSpot
    external: true
    url: http://www.crowdspot.com.au
