# Settings for the app
app:
  # HTML Title
  title: Transport Troubles
  # Header name
  name: Transport Troubles
  # Meta description that will show up in Google search results
  meta_description: _(Crowdsourcing perceptions of public transport in Victoria.)

  # When the map loads, existing places will be loaded in chunks. By default,
  # the size of the chunks will be a reasonable default dictated by the API
  # server. If you would like to override the chunk size, use this setting:
  # places_page_size: 100

  # Optional. List view is supported by default. Set to false to disable.
  # list_enabled: false


# Settings for map and layer configs
map:
  geolocation_enabled: false
  geolocation_onload: false

  geocoding_enabled: true
  geocoding_engine: 'Mapbox'
  geocode_field_label: _(Enter the street name and suburb...)
  geocode_bounding_box: [ 140.798, -39.300, 150.100, -33.930 ]  # minX, minY, maxX, maxY or top, left, bottom, right
  geocode_hint: [145, -38]
  geocode_auto_populate_spot_name: true

  options:
    center:
      lat: -37.82233
      lng: 144.95996
    zoom: 13
    minZoom: 7
    maxZoom: 18
    maxBounds: [ [-39.300, 140.798], [-33.930, 150.100] ] # bottom, left, top, right
  layers:
    - url: https://api.mapbox.com/styles/v1/aisey/cis1cannd0002gpm4571a8gkw/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiYWlzZXkiLCJhIjoiZVhQcWtnZyJ9.-YulcMjSuM7sQNxPYh26HQ
      attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  trainspot:
    index: 0
    label: _(Train Trouble Spot)
    rules:

      - condition: '"{{location_type}}" === "trainspot" && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/train-spot.svg
          shadowUrl: /static/css/images/master-pin-shadow.svg
          iconSize: [85, 41]
          iconAnchor: [42, 42]

      - condition: '"{{location_type}}" === "trainspot" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/spot-selected.svg
          shadowUrl: /static/css/images/master-pin-shadow.svg
          iconSize: [85, 41]
          shadowSize: [85, 41]
          iconAnchor: [42, 42]
  tramspot:
    index: 1
    label: _(Tram Trouble Spot)
    rules:

      - condition: '"{{location_type}}" === "tramspot" && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/tram-spot.svg
          shadowUrl: /static/css/images/master-pin-shadow.svg
          iconSize: [85, 41]
          iconAnchor: [42, 42]

      - condition: '"{{location_type}}" === "tramspot" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/spot-selected.svg
          shadowUrl: /static/css/images/master-pin-shadow.svg
          iconSize: [85, 41]
          shadowSize: [85, 41]
          iconAnchor: [42, 42]
  busspot:
    index: 2
    label: _(Bus Trouble Spot)
    rules:

      - condition: '"{{location_type}}" === "busspot" && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/bus-spot.svg
          shadowUrl: /static/css/images/master-pin-shadow.svg
          iconSize: [85, 41]
          iconAnchor: [42, 42]

      - condition: '"{{location_type}}" === "busspot" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/spot-selected.svg
          shadowUrl: /static/css/images/master-pin-shadow.svg
          iconSize: [85, 41]
          shadowSize: [85, 41]
          iconAnchor: [42, 42]
  likespot:
    index: 3
    label: _(Like Spot)
    rules:

      - condition: '"{{location_type}}" === "likespot" && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/like-spot.svg
          shadowUrl: /static/css/images/master-pin-shadow.svg
          iconSize: [85, 41]
          iconAnchor: [42, 42]

      - condition: '"{{location_type}}" === "likespot" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/spot-selected.svg
          shadowUrl: /static/css/images/master-pin-shadow.svg
          iconSize: [85, 41]
          shadowSize: [85, 41]
          iconAnchor: [42, 42]


activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: true
  add_button_label: _(Add a Spot)
  # Labels for the buttons that toggle the map and list views
  show_list_button_label: _(List All Spots)
  show_map_button_label: _(Show the Map)
  action_text: _(added)
  title: _(Tell us about your Transport Trouble..)
  action_text: _(added)
  anonymous_name: _(Someone)
  submit_button_label: _(Submit)

  location_item_name: location

  items:
    - prompt: _(What is the name of this spot?)
      type: text
      name: name
      attrs:
        - key: placeholder
          value: _(Street, Park, Landmark, etc.)
        - key: size
          value: 30
        - key: required
    - prompt: _(What type of Spot is this?)
      type: select
      options:
        - label: _(Choose One)
          value: ''
        - label: _(Train Trouble Spot)
          value: trainspot
        - label: _(Tram Trouble Spot)
          value: tramspot
        - label: _(Bus Trouble Spot)
          value: busspot
        - label: _(Like Spot)
          value: likespot
      name: location_type
      attrs:
        - key: required
    - prompt: _(What Train Trouble is happening here?)
      type: select
      optional: true
      options:
        - label: _(Choose One)
          value: ''
        - label: _(Running late)
          value: Running Late
        - label: _(Overcrowded)
          value: Overcrowded
        - label: _(Skipped station)
          value: Skipped station
        - label: _(Cancellation)
          value: Cancellation
        - label: _(Lack of service)
          value: Lack of service
        - label: _(Myki)
          value: Myki
        - label: _(Other)
          value: Other
      name: location_train_trouble
    - prompt: _(What Tram Trouble is happening here?)
      type: select
      optional: true
      options:
        - label: _(Choose One)
          value: ''
        - label: _(Running late)
          value: Running late
        - label: _(Overcrowded)
          value: Overcrowded
        - label: _(Skipped station)
          value: Skipped station
        - label: _(Cancellation)
          value: Cancellation
        - label: _(Lack of service)
          value: Lack of service
        - label: _(Myki)
          value: Myki
        - label: _(Other)
          value: Other
      name: location_tram_trouble
    - prompt: _(What Bus Trouble is happening here?)
      type: select
      optional: true
      options:
        - label: _(Choose One)
          value: ''
        - label: _(Running late)
          value: Running late
        - label: _(Overcrowded)
          value: Overcrowded
        - label: _(Skipped station)
          value: Skipped station
        - label: _(Cancellation)
          value: Cancellation
        - label: _(Lack of service)
          value: Lack of service
        - label: _(Myki)
          value: Myki
        - label: _(Other)
          value: Other
      name: location_bus_trouble
    - prompt: _(Please tell us more about this spot..)
      type: textarea
      name: description
      optional: false
      attrs:
        - key: placeholder
          value: _(Please describe...)
        - key: required
    - prompt: _(Please add an image of this spot if you have one)
      inputfile_label: _(Add Image)
      type: file
      name: my_image
      optional: true
      attrs:
        - key: accept
          value: image/*
    - prompt: _(Username (Letters only))
      type: text
      name: submitter_name
      sticky: true
      optional: true
      attrs:
        - key: placeholder
          value: _(This name will be visible)
        - key: size
          value: 30
        - key: pattern
          value: ^[a-zA-Z]+$
    - prompt: _(First Name (Letters only))
      type: text
      name: first_name
      sticky: true
      optional: true
      attrs:
        - key: placeholder
          value: _(This name will be hidden)
        - key: size
          value: 30
        - key: pattern
          value: ^[a-zA-Z]+$
    - prompt: _(Last Name (Letters only))
      type: text
      name: last_name
      sticky: true
      optional: true
      attrs:
        - key: placeholder
          value: _(This will be hidden)
        - key: size
          value: 30
        - key: pattern
          value: ^[a-zA-Z]+$
    - prompt: _(Suburb)
      type: text
      name: suburb
      sticky: true
      optional: true
      attrs:
        - key: placeholder
          value: _(Type suburb here)
        - key: size
          value: 30
    - prompt: _(Postcode (1000 - 9999))
      type: text
      name: postcode
      sticky: true
      optional: true
      attrs:
        - key: placeholder
          value: _(Type postcode here 1000 - 9999)
        - key: size
          value: 30
        - key: pattern
          value: ^([1-9][0-9][0-9][0-9])$
    - prompt: _(Phone number)
      type: number
      name: phone
      sticky: true
      optional: true
      attrs:
        - key: placeholder
          value: _(Type phone number here)
        - key: size
          value: 30
    - prompt: _(Please type your email below)
      type: email
      sticky: true
      name: private-submitter_email
      optional: true
      attrs:
        - key: placeholder
          value: _(Email address)
        - key: size
          value: 30

survey:
  submission_type: comments

  # Response config
  show_responses: true
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Submit Comment)
  items:
    - prompt: _(What do you think of this spot?)
      label: _(Comment)
      type: textarea
      name: comment
      attrs:
        - key: required
    - prompt: _(Your Name)
      type: text
      name: submitter_name
    - prompt: _(Please type your email below)
      type: email
      sticky: true
      name: private-submitter_email_comment
      optional: true
      attrs:
        - key: placeholder
          value: _(Email address)
        - key: size
          value: 30

support:
  submission_type: support
  submit_btn_text: _(Support)
  response_name: _(support)
  response_plural_name: _(supports)
  action_text: supported
  anonymous_name: _(Someone)

pages:
  - title: _(Welcome)
    slug: welcome
    name: overview
    start_page: true

  - title: _(Filter)
    pages:
      - title: _(Show All)
        url: /filter/all
        external: true
      - title: _(Train Spots)
        url: /filter/trainspot
        external: true
      - title: _(Tram Spots)
        url: /filter/tramspot
        external: true
      - title: _(Bus Spots)
        url: /filter/busspot
        external: true
      - title: _(Like Spots)
        url: /filter/likespot
        external: true


notifications:
  on_new_place: true
  submitter_email_field: private-submitter_email
