# The Shareabouts API dataset username & name used by this map.
# You MUST change this after creating a dataset.
api_root: http://localhost:8001/api/v1/
dataset: tom/bikespot

# And the associated API key.
dataset_api_key: YWY1YjMyNzU5YjRiZDljOTQwMGM0Nzhm

# Settings for the app
app:
  # HTML Title
  title: Public Transport Not Traffic
  # Header name
  name: Public Transport Not Traffic
  # Meta description that will show up in Google search results
  meta_description: CrowdSpot is a mapping tool to gather crowd sourced public input. Use it to collect suggested locations and comments in a social, engaging process.

  # When the map loads, existing places will be loaded in chunks. By default,
  # the size of the chunks will be a reasonable default dictated by the API
  # server. If you would like to override the chunk size, use this setting:
  # places_page_size: 100

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false
  options:
    center:
      lat: -37.81361
      lng: 144.96306
    zoom: 13
    minZoom: 12
    maxZoom: 18
  layers:
    - url: http://{s}.tiles.mapbox.com/v3/aisey.ggk2hf20/{z}/{x}/{y}.png
      attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  Bus Spot:
    label: _(Bus Spot)
    rules:
      - condition: '"{{location_type}}" === "Bus Spot"'
        # Display landmarks as icons
        
        icon:
          iconUrl: /static/css/images/bus.png
          iconSize: [85, 41]
          shadowUrl: /static/css/images/master-pin-shadow.png 
          shadowSize: [42,85]
          iconAnchor: [42, 42]
        focus_icon:
          iconUrl: /static/css/images/marker-focused.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]

  landmark:
    label: _(Tram Spot)
    rules:
      - condition: '"{{location_type}}" === "Tram Spot"'
        # Display landmarks as icons

        icon:
          iconUrl: /static/css/images/tram.png
          iconSize: [85, 41]
          shadowUrl: /static/css/images/master-pin-shadow.png 
          shadowSize: [42,85]
          iconAnchor: [42, 42]
        focus_icon:
          iconUrl: /static/css/images/marker-focused.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]
          
  landmark:
    label: _(Train Spot)
    rules:
      - condition: '"{{location_type}}" === "Train Spot"'
        # Display landmarks as icons

        icon:
          iconUrl: /static/css/images/train.png
          iconSize: [85, 41]
          shadowUrl: /static/css/images/master-pin-shadow.png 
          shadowSize: [42,85]
          iconAnchor: [42, 42]
        focus_icon:
          iconUrl: /static/css/images/marker-focused.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]       
          

# Defines place icons. See http://leaflet.cloudmade.com/reference.html#icon
# for documention of each property. Any omitted property will be undefined.

activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 5000

place:
  adding_supported: true
  add_button_label: _(Add a Spot)
  action_text: _(added)
  title: _(Tell us more...)
  action_text: _(created)
  anonymous_name: _(Someone)
  submit_button_label: _(Submit)
  items:
    - prompt: "What's here?"
      type: text
      name: name
      attrs:
        - key: placeholder
          value: Station, stop, landmark, etc.
        - key: size
          value: 30
    - prompt: What transport mode does this spot relate to?
      type: select
      options:
        - Please choose
        - Bus Spot
        - Tram Spot
        - Train Spot
      name: location_type
    - prompt: "What improvements would you like to see here?"
      type: textarea
      name: issue
      attrs:
        - key: placeholder
          value: Type description here...        
    - prompt: Add an Image
      inputfile_label: _(Add an Image)      
      type: file
      name: my_image
      optional: true
      attrs:
        - key: accept
          value: image/*
      name: location_type    
    - prompt: Your Name or Organisation
      type: text
      name: submitter_name
      attrs:
        - key: placeholder
          value: Type name here
        - key: size
          value: 30
    - prompt: Your email
      type: text
      name: private-submitter_email
      attrs:
        - key: placeholder
          value: Your email will be kept confidential
        - key: size
          value: 30             

survey:
  submission_type: comments

  # Response display config
  show_responses: true
  response_name: comment
  response_plural_name: comments
  action_text: commented on
  anonymous_name: Someone

  # Survey form config
  title: Leave a Comment
  form_link_text: Leave a Comment
  submit_btn_text: Comment
  items:
    - prompt: Comment
      label: Comment
      type: textarea
      name: comment
    - prompt: Your Name
      type: text
      name: submitter_name

support:
  submission_type: support
  submit_btn_text: Support This!
  action_text: "votes for"
  anonymous_name: A supporter

pages:
  - title: Welcome
    slug: welcome
    name: overview
    start_page: true

  - title: "Spots + Filter"
    slug: why
    name: why
    
  - title: "FAQS"
    slug: faqs
    name: faqs  

  - title: "Contact"
    slug: contact
    name: features

