# Settings for the app
app:
  # HTML Title
  title: CrowdSpot Demo
  # Header name
  name: CrowdSpot Demo
  # Meta description that will show up in Google search results
  meta_description: _(CrowdSpot creates custom maps that allow people to give input on geogrpahic locations. Use it to collect data in a social, engaging process.)

  # When the map loads, existing places will be loaded in chunks. By default,
  # the size of the chunks will be a reasonable default dictated by the API
  # server. If you would like to override the chunk size, use this setting:
  # places_page_size: 100

  # Optional. List view is supported by default. Set to false to disable.
  # list_enabled: false


# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false

  geocoding_enabled: false
  geocode_field_label: _(Enter the street name and suburb...)
  geocode_bounding_box: [-37.147182, 143.819274, -37.275679, 145.676826]  # top, left, bottom, right

  options:
    center:
      lat: -37.813239
      lng: 144.964431
    zoom: 13
    minZoom: 5
    maxZoom: 15
  layers:
    - url: https://api.mapbox.com/styles/v1/aisey/cio76ao69000ra5nkkrs4uuo4/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiYWlzZXkiLCJhIjoiZVhQcWtnZyJ9.-YulcMjSuM7sQNxPYh26HQ
      attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  safe:
    index: 0
    label: _(Safe Spot)
    rules:
      - condition: '"{{location_type}}" === "safe" && {{map.zoom}} < 13 && {{layer.focused}} === false'
        # Display landmarks as circles (vectors) when zoomed out

        style:
          color: '#45BA00'
          radius: 15
          weight: 3
          opacity: 0.7
          fillOpacity: 0.5

      - condition: '"{{location_type}}" === "safe" && {{map.zoom}} >= 13 && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/radspotgood.svg
          shadowUrl: /static/css/images/master-pin-shadow.svg
          iconSize: [85, 41]
          iconAnchor: [42, 42]

      - condition: '"{{location_type}}" === "safe" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/spot-selected.svg
          shadowUrl: /static/css/images/master-pin-shadow.svg
          iconSize: [85, 41]
          shadowSize: [85, 41]
          iconAnchor: [42, 42]
  unsafe:
    index: 1
    label: _(Unsafe Spot)
    rules:
      - condition: '"{{location_type}}" === "unsafe" && {{map.zoom}} < 13 && {{layer.focused}} === false'
        # Display landmarks as circles (vectors) when zoomed out

        style:
          color: '#EC611A'
          radius: 15
          weight: 3
          opacity: 0.7
          fillOpacity: 0.5

      - condition: '"{{location_type}}" === "unsafe" && {{map.zoom}} >= 13 && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/radspot.svg
          shadowUrl: /static/css/images/master-pin-shadow.svg
          iconSize: [85, 41]
          iconAnchor: [42, 42]

      - condition: '"{{location_type}}" === "unsafe" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/spot-selected.svg
          shadowUrl: /static/css/images/master-pin-shadow.svg
          iconSize: [85, 41]
          shadowSize: [85, 41]
          iconAnchor: [42, 42]


activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: true
  add_button_label: _(Add a Spot)
  # Labels for the buttons that toggle the map and list views
  show_list_button_label: _(List All Spots)
  show_map_button_label: _(Show the Map)
  action_text: _(added)
  title: _(Complete the form below to add your spot..)
  action_text: _(added)
  anonymous_name: _(Someone)
  submit_button_label: _(Submit)

  location_item_name: location

  items:
    - prompt: _(What is the name of this spot?)
      type: text
      name: name
      attrs:
        - key: placeholder
          value: _(Street, Park, Landmark, etc.)
        - key: size
          value: 30
        - key: required
    - prompt: _(What type of spot is this?)
      type: select
      options:
        - label: _(Choose One)
          value: ''
        - label: _(Safe Spot)
          value: safe
        - label: _(Unsafe Spot)
          value: unsafe
      name: location_type
      attrs:
        - key: required
    - prompt: _(Tell us more about this spot if you want..)
      type: textarea
      name: description
      optional: true
      attrs:
        - key: placeholder
          value: _(Please describe...)
        - key: required
    - prompt: _(You can add an image of this spot if you have one)
      inputfile_label: _(Add Image)
      type: file
      name: my_image
      optional: true
      attrs:
        - key: accept
          value: image/*
    - prompt: _(Your name or username)
      type: text
      name: submitter_name
      sticky: true
      optional: true
      attrs:
        - key: placeholder
          value: _(This name will be visible)
        - key: size
          value: 30
    - prompt: _(Please type your email below)
      type: text
      sticky: true
      name: private-submitter_email
      optional: true
      attrs:
        - key: placeholder
          value: _(Email address)
        - key: size
          value: 30

survey:
  submission_type: comments

  # Response config
  show_responses: true
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Submit Comment)
  items:
    - prompt: _(What do you think of this spot?)
      label: _(Comment)
      type: textarea
      name: comment
      attrs:
        - key: required
    - prompt: _(Your Name)
      type: text
      name: submitter_name

support:
  submission_type: support
  submit_btn_text: _(Support)
  response_name: _(support)
  response_plural_name: _(supports)
  action_text: supported
  anonymous_name: _(Someone)

pages:
  - title: _(Welcome)
    slug: welcome
    name: overview
    start_page: true

  - title: _(Filter)
    pages:
      - title: _(Show All)
        url: /filter/like
        external: true
      - title: _(Safe Spots)
        url: /filter/issue
        external: true
      - title: _(Unsafe Spots)
        url: /filter/idea
        external: true
  - title: _(Contact)
    pages:
      - title: _(Website)
        external: true
        url: http://www.crowdspot.com.au/contact/
      - title: _(Twitter)
        external: true
        url: https://twitter.com/Crowd_Spot
      - title: _(Facebook)
        external: true
        url: https://www.facebook.com/pages/CrowdSpot/314531231976999



notifications:
  on_new_place: true
  submitter_email_field: private-submitter_email
