# Settings for the app
app:
  # HTML Title
  title: Our Creek
  # Header name
  name: Our Creek
  # Meta description that will show up in Google search results
  meta_description: _(CrowdSpot creates custom maps that allow people to collaborate on giving input for geographic locations. Use it to collect data in a social, engaging process.)

  # When the map loads, existing places will be loaded in chunks. By default,
  # the size of the chunks will be a reasonable default dictated by the API
  # server. If you would like to override the chunk size, use this setting:
  # places_page_size: 100

  # Optional. List view is supported by default. Set to false to disable.
  # list_enabled: false
 

# Settings for map and layer configs
map:
  geolocation_enabled: false
  geolocation_onload: false

  geocoding_enabled: false
  geocode_field_label: _(Enter the street name and suburb...)
  geocode_bounding_box: [-37.147182, 143.819274, -36.275278, 144.98657200000002]  # top, left, bottom, right

  options:
    center:
      lat: -37.749136
      lng: 144.930901
    zoom: 15
    minZoom: 14
    maxZoom: 18
    maxBounds: [ [-37.862356, 144.831557], [-37.672215, 145.002172] ]
  layers: 
    - url: http://{s}.tiles.mapbox.com/v3/aisey.o838am6m/{z}/{x}/{y}.png
      attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  legend:
    index: 0
    label: _(SPOT TYPES)
    rules:
      - condition: '"{{location_type}}" === "car" && {{map.zoom}} < 15 && {{layer.focused}} === false'
        # Display landmarks as circles (vectors) when zoomed out

        style:
          color: '#FF1609'
          radius: 5
          weight: 1
          opacity: 0.9
          fillOpacity: 0.7

      - condition: '"{{location_type}}" === "car" && {{map.zoom}} >= 14 && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/legend.png
          shadowUrl: /static/css/images/master-pin-shadow.png
          iconSize: [85, 41]
          iconAnchor: [42, 42]

      - condition: '"{{location_type}}" === "car" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/marker-f39914.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]
  environment:
    index: 1
    label: _(Environment Spot)
    rules:
      - condition: '"{{location_type}}" === "environment" && {{map.zoom}} < 12 && {{layer.focused}} === false'
        # Display landmarks as circles (vectors) when zoomed out

        style:
          color: '#45BA00'
          radius: 5
          weight: 1
          opacity: 0.9
          fillOpacity: 0.7

      - condition: '"{{location_type}}" === "environment" && {{map.zoom}} >= 12 && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/master-pin-green-leaf.png
          shadowUrl: /static/css/images/master-pin-shadow.png
          iconSize: [85, 41]
          iconAnchor: [42, 42]

      - condition: '"{{location_type}}" === "environment" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/marker-f95016.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]
  transport:
    index: 2
    label: _(Transport Spot)
    rules:
      - condition: '"{{location_type}}" === "transport" && {{map.zoom}} < 12 && {{layer.focused}} === false'
        # Display landmarks as circles (vectors) when zoomed out

        style:
          color: '#EC611A'
          radius: 5
          weight: 1
          opacity: 0.9
          fillOpacity: 0.7

      - condition: '"{{location_type}}" === "transport" && {{map.zoom}} >= 12 && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/master-pin-green-wheel.png
          shadowUrl: /static/css/images/master-pin-shadow.png
          iconSize: [85, 41]
          iconAnchor: [42, 42]

      - condition: '"{{location_type}}" === "transport" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/marker-f95016.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]
  history:
    index: 3
    label: _(History Spot)
    rules:
      - condition: '"{{location_type}}" === "history" && {{map.zoom}} < 12 && {{layer.focused}} === false'
        # Display landmarks as circles (vectors) when zoomed out

        style:
          color: '#FF1609'
          radius: 5
          weight: 1
          opacity: 0.9
          fillOpacity: 0.7

      - condition: '"{{location_type}}" === "history" && {{map.zoom}} >= 12 && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/master-pin-red-history.png
          shadowUrl: /static/css/images/master-pin-shadow.png
          iconSize: [85, 41]
          iconAnchor: [42, 42]

      - condition: '"{{location_type}}" === "history" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/marker-f95016.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]
  attraction:
    index: 4
    label: _(Attraction Spot)
    rules:
      - condition: '"{{location_type}}" === "attraction" && {{map.zoom}} < 12 && {{layer.focused}} === false'
        # Display landmarks as circles (vectors) when zoomed out

        style:
          color: '#FEC500'
          radius: 5
          weight: 1
          opacity: 0.9
          fillOpacity: 0.7

      - condition: '"{{location_type}}" === "attraction" && {{map.zoom}} >= 12 && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/master-pin-blue-camera.png
          shadowUrl: /static/css/images/master-pin-shadow.png
          iconSize: [85, 41]
          iconAnchor: [42, 42]

      - condition: '"{{location_type}}" === "attraction" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/marker-f95016.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]
  idea:
    index: 5
    label: _(Idea Spot)
    rules:
      - condition: '"{{location_type}}" === "idea" && {{map.zoom}} < 12 && {{layer.focused}} === false'
        # Display landmarks as circles (vectors) when zoomed out

        style:
          color: '#FEC500'
          radius: 5
          weight: 1
          opacity: 0.9
          fillOpacity: 0.7

      - condition: '"{{location_type}}" === "idea" && {{map.zoom}} >= 12 && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/master-pin-yellow-idea.png
          shadowUrl: /static/css/images/master-pin-shadow.png
          iconSize: [85, 41]
          iconAnchor: [42, 42]

      - condition: '"{{location_type}}" === "idea" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/marker-f95016.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]                     
                            
                          
activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: true
  add_button_label: _(Add a Spot)
  # Labels for the buttons that toggle the map and list views
  show_list_button_label: _(List All Spots)
  show_map_button_label: _(Show the Map)
  action_text: _(added)
  title: _(Tell us about the Moonee Ponds Creek)
  action_text: _(added)
  anonymous_name: _(Someone)
  submit_button_label: _(Submit)

  location_item_name: location

  items:
    - prompt: _(What is the name of this spot?)
      type: text
      name: name
      attrs:
        - key: placeholder
          value: _(Street, Park, Landmark, etc.)
        - key: size
          value: 30
        - key: required
    - prompt: _(What type of spot is this?)
      type: select
      options:
        - label: _(Choose One)
          value: ''
        - label: _(Environment Spot)
          value: environment 
        - label: _(Transport Spot)
          value: transport      
        - label: _(History Spot)
          value: history
        - label: _(Attraction Spot)
          value: attraction
        - label: _(Idea Spot)
          value: idea  
      name: location_type
      attrs:
        - key: required
    - prompt: _(Is this a positive or negative Environmet Spot of the creek?)
      type: select
      options:
        - label: _(Choose One)
          value: ''
        - label: _(Positive)
          value: positive 
        - label: _(Negative)
          value: negative       
      name: enviro_pos_neg
      optional: true
    - prompt: _(What transport mode does this transport spot most relate to?)
      type: select
      options:
        - label: _(Choose One)
          value: ''
        - label: _(Walking)
          value: walking 
        - label: _(Bike riding)
          value: bike      
        - label: _(Public Transport)
          value: pt
        - label: _(Car)
          value: car  
      name: transport_mode 
    - prompt: _(Is this a positive or negative Transport Spot of the creek?)
      type: select
      options:
        - label: _(Choose One)
          value: ''
        - label: _(Positive)
          value: positive 
        - label: _(Negative)
          value: negative       
      name: transport_pos_neg
      optional: true                                         
    - prompt: _(Please tell us more about this Environment Spot?)
      type: textarea
      name: descriptions_environment
      optional: true
      attrs:
        - key: placeholder
          value: _(Please describe...)
    - prompt: _(Please tell us more about this Transport Spot?)
      type: textarea
      name: descriptions_transport
      optional: true
      attrs:
        - key: placeholder
          value: _(Please describe...)
    - prompt: _(Please tell us more about this Hsitory Spot?)
      type: textarea
      name: descriptions_history
      optional: true
      attrs:
        - key: placeholder
          value: _(Please share any history or stories about the creek...)
    - prompt: _(Please tell us more about this Attraction Spot?)
      type: textarea
      name: descriptions_attraction
      optional: true
      attrs:
        - key: placeholder
          value: _(Please tell us about any of your favourite things along the creek...)
    - prompt: _(Please tell us more about this Idea Spot?)
      type: textarea
      name: descriptions_idea
      optional: true
      attrs:
        - key: placeholder
          value: _(Please share any great ideas you have for the creek...)                                                                          
    - prompt: _(Please add an image if you have one)
      inputfile_label: _(Add Image)
      type: file
      name: my_image
      optional: true
      attrs:
        - key: accept
          value: image/*    
    - prompt: _(Your age)
      type: select
      options:
        - label: _(Choose One)
          value: ''
        - label: _(< 14)
          value: '<14'
        - label: _(15-19)
          value: 15-19
        - label: _(20-24)
          value: 20-24
        - label: _(25-34)
          value: 25-34
        - label: _(35-44)
          value: 35-44
        - label: _(45-54)
          value: 45-54
        - label: _(55-64)
          value: 55-64
        - label: _(65-74)
          value: 65-74
        - label: _(>75)
          value: '>75'          
      name: age
      sticky: true
      optional: true
    - prompt: _(Your gender)
      type: select
      options:
        - label: _(Choose One)
          value: ''
        - label: _(Male)
          value: male
        - label: _(Female)
          value: female
        - label: _(Other)
          value: other        
      name: gender
      sticky: true
      optional: true                               
    - prompt: _(Your suburb or town)
      sticky: true
      type: text
      attrs:
        - key: placeholder
          value: _(suburb)
        - key: size
          value: 30           
      name: suburb
      optional: true                                              
    - prompt: _(Your name)
      type: text
      name: submitter_name
      sticky: true
      optional: true
      attrs:
        - key: placeholder
          value: _(Type name)
        - key: size
          value: 30
    - prompt: _(Would you like to stay informed about this project?)
      type: select
      options:
        - label: _(Choose One)
          value: ''
        - label: _(Yes - please send updates)
          value: yesplease 
        - label: _(No thanks - no emails please)
          value: nothanks
      name: location_updates
      optional: true
      sticky: true                  
    - prompt: _(Please type your email below)
      type: text
      sticky: true
      name: private-submitter_email
      optional: true
      attrs:
        - key: placeholder
          value: _(Email address)
        - key: size
          value: 30                

survey:
  submission_type: comments

  # Response config
  show_responses: true
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
      attrs:
        - key: required
    - prompt: _(Your Name)
      type: text
      name: submitter_name

support:
  submission_type: support
  submit_btn_text: _(Like)
  response_name: _(like)
  response_plural_name: _(likes)
  action_text: liked
  anonymous_name: _(Someone)

pages:
  - title: _(Welcome)
    slug: welcome
    name: overview
    start_page: true
    
  - title: _(Go to Suburb)
    slug: suburb
    url: /static/pages/suburb.html
    
  - title: _(Filter)
    pages:
      - title: _(Show All)
        url: /
        external: true
      - title: _(Environment Spots)
        url: /filter/environment
        external: true
      - title: _(Transport Spots)
        url: /filter/transport
        external: true
      - title: _(History Spots)
        url: /filter/history
        external: true
      - title: _(Like Spots)
        url: /filter/like
        external: true
      - title: _(Idea Spots)
        url: /filter/idea
        external: true   
                         

notifications:
  on_new_place: true
  submitter_email_field: private-submitter_email