# Settings for the app
app:
  # HTML Title
  title: Plan Safe Cities
  # Header name
  name: Plan Safe Cities
  # Meta description that will show up in Google search results
  meta_description: _(Crowdsourcing perceptions of safety in the city of Melbourne)

  # When the map loads, existing places will be loaded in chunks. By default,
  # the size of the chunks will be a reasonable default dictated by the API
  # server. If you would like to override the chunk size, use this setting:
  # places_page_size: 100

  # Optional. List view is supported by default. Set to false to disable.
  # list_enabled: false


# Settings for map and layer configs
map:
  geolocation_enabled: false
  geolocation_onload: false

  geocoding_enabled: false
  geocode_field_label: _(Enter the street name and suburb...)
  geocode_bounding_box: [-37.147182, 143.819274, -37.275679, 145.676826]  # top, left, bottom, right

  options:
    center:
      lat: -37.81840
      lng: 144.97061
    zoom: 13
    minZoom: 5
    maxZoom: 18
  layers:
    - url: https://api.mapbox.com/styles/v1/aisey/cio76ao69000ra5nkkrs4uuo4/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiYWlzZXkiLCJhIjoiZVhQcWtnZyJ9.-YulcMjSuM7sQNxPYh26HQ
      attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  happy:
    index: 0
    label: _(Happy Spot)
    rules:

      - condition: '"{{location_type}}" === "happy" && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/plan-marker-happy.svg
          shadowUrl: /static/css/images/markers/master-pin-shadow.svg
          iconSize: [27, 37]
          iconAnchor: [12, 40]
          shadowSize: [34, 17]
          shadowAnchor: [0, 21]

      - condition: '"{{location_type}}" === "happy" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/plan-marker-happy.svg
          shadowUrl: /static/css/images/markers/master-pin-shadow.svg
          iconSize: [46, 63]
          iconAnchor: [23, 63]
          shadowSize: [60, 32]
          shadowAnchor: [0, 32]

  sad:
    index: 1
    label: _(Sad Spot)
    rules:

      - condition: '"{{location_type}}" === "sad" && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/plan-marker-sad.svg
          shadowUrl: /static/css/images/markers/master-pin-shadow.svg
          iconSize: [27, 37]
          iconAnchor: [12, 40]
          shadowSize: [34, 17]
          shadowAnchor: [0, 21]

      - condition: '"{{location_type}}" === "sad" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/plan-marker-sad.svg
          shadowUrl: /static/css/images/markers/master-pin-shadow.svg
          iconSize: [46, 63]
          iconAnchor: [23, 63]
          shadowSize: [60, 32]
          shadowAnchor: [0, 32]

activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: true
  add_button_label: _(Add a Spot)
  # Labels for the buttons that toggle the map and list views
  show_list_button_label: _(List All Spots)
  show_map_button_label: _(Show the Map)
  action_text: _(added)
  title: _(Tell us about you experience)
  action_text: _(added)
  anonymous_name: _(Someone)
  submit_button_label: _(Submit)

  location_item_name: location

  items:
    # - prompt: _(What is the name of this spot?)
    #   type: text
    #   name: name
    #   attrs:
    #     - key: placeholder
    #       value: _(Street, Park, Landmark, etc.)
    #     - key: size
    #       value: 30
    #     - key: required
    - prompt: _(Did you have a happy or sad experience?)
      type: multi-radio
      name: location_type
      attrs:
        - key: required
        - key: class
      radios:
        - label: _(Happy Spot)
          value: happy
        - label: _(Sad Spot)
          value: sad
    - prompt: _(How do you feel at this Happy Spot?)
      type: multi-checkbox
      name: happy_feel
      optional: true
      checkboxes:
        - label: _(Relaxed)
          value: relaxed
        - label: _(Excited)
          value: excited
        - label: _(Satisfied)
          value: satisfied
        - label: _(Trust)
          value: trust
        - label: _(Love)
          value: love
    - prompt: _(How do you feel at this Sad Spot?)
      type: multi-checkbox
      name: sad_feel
      optional: true
      checkboxes:
        - label: _(Scared)
          value: scared
        - label: _(Angry)
          value: angry
        - label: _(Frustrated)
          value: frustrated
        - label: _(Disgust)
          value: disgust
        - label: _(Creepy)
          value: creepy
    - prompt: _(What time does this experience relate to?)
      type: multi-radio
      name: time
      attrs:
        - key: required
      radios:
        - label: _(Day Spot)
          value: day
        - label: _(Night Spot)
          value: night
        - label: _(Any time)
          value: anytime
    - prompt: _(Please tell us more about this spot if you want. This could be a story or experience you might like to share.)
      type: textarea
      name: description
      optional: true
      attrs:
        - key: placeholder
          value: _(Please describe...)
    - prompt: _(You can add an image of this spot if you have one)
      inputfile_label: _(Add Image)
      type: file
      name: my_image
      optional: true
      attrs:
        - key: accept
          value: image/*
    - prompt: _(If you have any <strong>ideas</strong> to improve this spot, please decribe them below.)
      type: textarea
      name: description_ideas
      optional: true
      attrs:
        - key: placeholder
          value: _(Please describe...)
    - prompt: _(Your name or username)
      type: text
      name: submitter_name
      sticky: true
      optional: true
      attrs:
        - key: placeholder
          value: _(This name will be visible)
        - key: size
          value: 30
    - prompt: _(Please type your email below)
      type: text
      sticky: true
      name: private-submitter_email
      optional: true
      attrs:
        - key: placeholder
          value: _(Email address)
        - key: size
          value: 30

survey:
  submission_type: comments

  # Response config
  show_responses: true
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Submit Comment)
  items:
    - prompt: _(What do you think of this spot? Do you agree? Any advice or tips for this spot?)
      label: _(Comment)
      type: textarea
      name: comment
      attrs:
        - key: required
    - prompt: _(Your Name)
      type: text
      name: submitter_name

support:
  submission_type: support
  submit_btn_text: _(Support)
  response_name: _(support)
  response_plural_name: _(supports)
  action_text: supported
  anonymous_name: _(Someone)

pages:
  - title: _(Welcome)
    slug: welcome
    name: overview
    start_page: true

  - title: _(Filter)
    pages:
      - title: _(Show All)
        url: /filter/all
        external: true
      - title: _(Safe Spots)
        url: /filter/safe
        external: true
      - title: _(Unsafe Spots)
        url: /filter/unsafe
        external: true


notifications:
  on_new_place: true
  submitter_email_field: private-submitter_email
