# The Shareabouts API dataset username & name used by this map.
# You MUST change this after creating a dataset.
api_root: http://localhost:8001/api/v1/
dataset: tom/bikespot

# And the associated API key.
dataset_api_key: YWY1YjMyNzU5YjRiZDljOTQwMGM0Nzhm

# Settings for the app
app:
  # HTML Title
  title: SLF Eco-City Map
  # Header name
  name: SLF Eco-City Map
  # Meta description that will show up in Google search results
  meta_description: CrowdSpot is a mapping tool to gather crowd sourced public input. Use it to collect suggested locations and comments in a social, engaging process.

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: true
  options:
    center:
      lat: -37.81361
      lng: 144.96306
    zoom: 14
    minZoom: 10
    maxZoom: 17
  base_layer:
    url: http://{s}.tiles.mapbox.com/v3/mapbox.mapbox-streets/{z}/{x}/{y}.png
    attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'
  layers: []

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  Attraction:
    default: blue
    focused: red
  Feature:
    default: blue
    focused: red
  Event:
    default: blue
    focused: red

# Defines place icons. See http://leaflet.cloudmade.com/reference.html#icon
# for documention of each property. Any omitted property will be undefined.
place_type_icons:
  blue:
    iconUrl: /static/css/images/feature-point.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  red:
    iconUrl: /static/css/images/marker-focused.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41


activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 5000

place:
  adding_supported: true
  add_button_label: Add a Spot
  action_text: added
  title: Tell us more...
  action_text: created
  anonymous_name: Someone
  submit_button_label: Submit
  items:
    - prompt: Spot Name
      type: text
      name: name
      attrs:
        - key: placeholder
          value: Spot Name
        - key: size
          value: 30
    - prompt: Spot Type
      type: select
      options:
        - Attraction
        - Feature
        - Event
      name: location_type
    - prompt: Your Name
      type: text
      name: submitter_name
      optional: true
      attrs:
        - key: placeholder
          value: Name
        - key: size
          value: 30
    - prompt: Description
      type: textarea
      name: description
      optional: true
      attrs:
        - key: placeholder
          value: Description...

survey:
  submission_type: comments

  # Response display config
  show_responses: true
  response_name: comment
  response_plural_name: comments
  action_text: commented on
  anonymous_name: Someone

  # Survey form config
  title: Leave a Comment
  form_link_text: Leave a Comment
  submit_btn_text: Comment
  items:
    - prompt: Comment
      label: Comment
      type: textarea
      name: comment
    - prompt: Your Name
      type: text
      name: submitter_name

support:
  submission_type: support
  submit_btn_text: Support This!
  action_text: "supported"
  anonymous_name: Someone

pages:
  - title: About
    slug: about
    url: /static/pages/overview.html
    start_page: true

  - title: "Why CrowdSpot?"
    slug: why
    url: /static/pages/why.html

  - title: Features
    slug: features
    url: /static/pages/features.html

  - title: CrowdSpot
    external: true
    url: http://www.crowdspot.com.au
