# The Shareabouts API dataset username & name used by this map.
# You MUST change this after creating a dataset.
api_root: http://localhost:8001/api/v1/
dataset: tom/bikespot

# And the associated API key.
dataset_api_key: YWY1YjMyNzU5YjRiZDljOTQwMGM0Nzhm

# Settings for the app
app:
  # HTML Title
  title: Plenty Gorge Park
  # Header name
  name: Plenty Gorge Park
  # Meta description that will show up in Google search results
  meta_description: CrowdSpot specialise in map-based community engagement. Gather crowd sourced public input to collect data on locations in a social, engaging process.

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false
  options:
    center:
      lat: -37.6495776829716
      lng: 145.10433197021484
    zoom: 14
    minZoom: 14
    maxZoom: 18
  base_layer:
    url: http://{s}.tiles.mapbox.com/v3/aisey.i02j1dp7/{z}/{x}/{y}.png
    attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'
  layers: []

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  Like Spot:
    default: yellow
    focused: focused
  Dislike Spot:
    default: red
    focused: focused  
  Activity Spot:
    default: orange
    focused: focused
  Idea Spot:
    default: blue
    focused: focused

# Defines place icons. See http://leaflet.cloudmade.com/reference.html#icon
# for documention of each property. Any omitted property will be undefined.
place_type_icons:
  orange:
    iconUrl: /static/css/images/pg_activity_orange.png
    shadowUrl: /static/css/images/master-pin-shadow.png
    iconSize:
      width: 85
      height: 41
    shadowSize:
      width: 42
      height: 85
    iconAnchor:
      x: 42
      y: 42
  blue:
    iconUrl: /static/css/images/pg_idea_blue.png
    shadowUrl: /static/css/images/master-pin-shadow.png
    iconSize:
      width: 85
      height: 41
    shadowSize:
      width: 42
      height: 85
    iconAnchor:
      x: 42
      y: 42
  yellow:
    iconUrl: /static/css/images/pg_like_yellow.png
    shadowUrl: /static/css/images/master-pin-shadow.png
    iconSize:
      width: 85
      height: 41
    shadowSize:
      width: 42
      height: 85
    iconAnchor:
      x: 42
      y: 42 
  red:
    iconUrl: /static/css/images/pg_dislike_brown.png
    shadowUrl: /static/css/images/master-pin-shadow.png
    iconSize:
      width: 85
      height: 41
    shadowSize:
      width: 42
      height: 85
    iconAnchor:
      x: 42
      y: 42       
  focused:
    iconUrl: /static/css/images/marker-focused.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41

activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 5000

place:
  adding_supported: true
  add_button_label: Add a Spot
  action_text: added
  title: Tell us about your spot! Is it something you like or dislike at Plenty Gorge, an activity you do here or your great idea for an improvement?
  action_text: created
  anonymous_name: Someone
  submit_button_label: Submit
  items:
    - prompt: What type of spot is this?
      type: select
      options:
        - Please choose
        - Like Spot
        - Dislike Spot
        - Activity Spot
        - Idea Spot
      name: location_type
    - prompt: "Where is this spot?"
      type: text
      name: name
      attrs:
        - key: placeholder
          value: Street, landmark, area, etc.
        - key: size
          value: 30
    - prompt: "What do you like at this spot?"
      type: textarea
      optional: true
      name: text_like
      attrs:
        - key: placeholder
          value: Type here...  
    - prompt: "What do you dislike at this spot?"
      type: textarea
      optional: true
      name: text_dislike
      attrs:
        - key: placeholder
          value: Type here...       
    - prompt: "What activity do you do at this spot?"
      type: textarea
      optional: true
      name: text_activity
      attrs:
        - key: placeholder
          value: Type here...
    - prompt: "What's your great idea for this spot?"
      type: textarea
      optional: true
      name: text_idea
      attrs:
        - key: placeholder
          value: Type here...           
    - prompt: Do you...
      type: select
      options:
        - Please choose
        - Live in the area
        - Visit the area
        - Work in the area
      name: category         
    - prompt: Add an Image
      inputfile_label: _(Add an Image)      
      type: file
      name: my_image
      optional: true
      attrs:
        - key: accept
          value: image/*
      name: location_type    
    - prompt: Your name
      type: text
      name: submitter_name
      attrs:
        - key: placeholder
          value: Will be visible...
        - key: size
          value: 30
    - prompt: Your email
      optional: true
      type: text
      name: private-submitter_email
      attrs:
        - key: placeholder
          value: Kept confidential and used for feedback
        - key: size
          value: 30
    - prompt: How often do you visit the park?
      type: select
      options:
        - Please choose
        - More than once a week
        - Weekly
        - Monthly
        - Infrequently
      name: often       
    - prompt: Your postcode
      type: text
      name: postcode
      attrs:
        - key: placeholder
          value: Type postcode here..                    

survey:
  submission_type: comments

  # Response display config
  show_responses: true
  response_name: comment
  response_plural_name: comments
  action_text: commented on
  anonymous_name: A supporter

  # Survey form config
  title: Leave a Comment
  form_link_text: Leave a Comment
  submit_btn_text: Submit comment
  items:
    - prompt: Comment
      label: Comment
      type: textarea
      name: comment
      attrs:
        - key: placeholder
          value: Type comment here..
    - prompt: Your Name
      type: text
      name: submitter_name
      attrs:
        - key: placeholder
          value: Type name here..
    - prompt: Your email
      type: text
      name: private-submitter_email
      attrs:
        - key: placeholder
          value: Kept confidential and used for feedback

support:
  submission_type: support
  submit_btn_text: Support this!
  action_text: "supported"
  anonymous_name: Someone

pages:
  - title: Welcome
    slug: welcome
    name: overview
    start_page: true

  - title: "Spot Types"
    slug: why
    name: why
    
  - title: "FAQs"
    slug: faqs
    name: faqs  

